/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 09-Oct-2017 11:48:44
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017a/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */

#include <csl_intc.h>


#define COEFFICIENTS_LENGTH 101

const Int16 COEFFICIENTS[COEFFICIENTS_LENGTH] = {
     0,      0,      0,      1,      1,     -1,     -3,     -2,      4,
     7,      0,    -12,    -12,      8,     25,     12,    -26,    -40,
     0,     55,     49,    -31,    -94,    -41,     88,    131,      0,
  -170,   -147,     90,    266,    115,   -238,   -350,      0,    443,
   381,   -233,   -686,   -298,    626,    938,      0,  -1271,  -1159,
   767,   2541,   1311,  -3664,  -9621,  20480,  -9621,  -3664,   1311,
  2541,    767,  -1159,  -1271,      0,    938,    626,   -298,   -686,
  -233,    381,    443,      0,   -350,   -238,    115,    266,     90,
  -147,   -170,      0,    131,     88,    -41,    -94,    -31,     49,
    55,      0,    -40,    -26,     12,     25,      8,    -12,    -12,
     0,      7,      4,     -2,     -3,     -1,      1,      1,      0,
     0,      0
//        0,      0,      0,      1,      1,     -1,     -3,     -2,      4,
//        7,      0,    -12,    -12,      8,     25,     12,    -26,    -40,
//        0,     55,     49,    -31,    -94,    -41,     88,    131,      0,
//     -170,   -147,     90,    266,    115,   -238,   -350,      0,    443,
//      381,   -233,   -686,   -298,    626,    938,      0,  -1271,  -1159,
//      767,   2541,   1311,  -3664,  -9621,  20480,  -9621,  -3664,   1311,
//     2541,    767,  -1159,  -1271,      0,    938,    626,   -298,   -686,
//     -233,    381,    443,      0,   -350,   -238,    115,    266,     90,
//     -147,   -170,      0,    131,     88,    -41,    -94,    -31,     49,
//       55,      0,    -40,    -26,     12,     25,      8,    -12,    -12,
//        0,      7,      4,     -2,     -3,     -1,      1,      1,      0,
//        0,      0
};

