/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 25-Sep-2017 12:39:29
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 101
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,15 -> [-1 1)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,30 -> [-4 4)  (auto determined)
 *   Product         : s31,30 -> [-1 1)  (auto determined)
 *   Accumulator     : s33,30 -> [-4 4)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
/*
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017a/extern/include/tmwtypes.h 
 */
#define COEFFICIENTS_LENGTH 101
const Int16 COEFFICIENTS[COEFFICIENTS_LENGTH] = {
        0,      0,      0,      0,     -1,     -1,     -2,     -4,     -6,
       -8,    -10,    -13,    -15,    -17,    -18,    -17,    -14,     -8,
        0,     12,     27,     45,     66,     90,    115,    139,    162,
      180,    192,    196,    188,    166,    129,     74,      0,    -93,
     -206,   -338,   -485,   -647,   -818,   -996,  -1175,  -1349,  -1515,
    -1666,  -1797,  -1904,  -1983,  -2032,  30720,  -2032,  -1983,  -1904,
    -1797,  -1666,  -1515,  -1349,  -1175,   -996,   -818,   -647,   -485,
     -338,   -206,    -93,      0,     74,    129,    166,    188,    196,
      192,    180,    162,    139,    115,     90,     66,     45,     27,
       12,      0,     -8,    -14,    -17,    -18,    -17,    -15,    -13,
      -10,     -8,     -6,     -4,     -2,     -1,     -1,      0,      0,
        0,      0
};
