/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 09-Oct-2017 11:55:13
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017a/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 51;
const int16_T B[51] = {
        0,      0,     -2,     -5,      5,     21,     13,    -35,    -67,
        0,    129,    133,    -95,   -323,   -159,    376,    623,      0,
     -996,   -970,    678,   2349,   1255,  -3593,  -9574,  20480,  -9574,
    -3593,   1255,   2349,    678,   -970,   -996,      0,    623,    376,
     -159,   -323,    -95,    133,    129,      0,    -67,    -35,     13,
       21,      5,     -5,     -2,      0,      0
};
