/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 23-Oct-2017 12:41:43
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I, Second-Order Sections
 * Number of Sections  : 10
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,14 -> [-2 2)
 * Denominator         : s16,14 -> [-2 2)
 * Scale Values        : s16,15 -> [-1 1)
 * Input               : s16,15 -> [-1 1)
 * Output              : s16,15 -> [-1 1)
 * Numerator State     : s16,15 -> [-1 1)
 * Denominator State   : s16,15 -> [-1 1)
 * Numerator Prod      : s32,29 -> [-4 4)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s40,29 -> [-1024 1024)
 * Denominator Accum   : s40,29 -> [-1024 1024)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017a/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 21
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
     3177,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     3177,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     2859,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     2859,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     2283,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     2283,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     1507,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
     1507,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
      672,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
      672,      0,      0
  },
  {
    16384,      0, -16384
  },
  {
    14603,      0,      0
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    16384,      0,      0
  },
  {
    16384, -28197,  16163
  },
  {
    16384,      0,      0
  },
  {
    16384, -32429,  16326
  },
  {
    16384,      0,      0
  },
  {
    16384, -28305,  15760
  },
  {
    16384,      0,      0
  },
  {
    16384, -32268,  16199
  },
  {
    16384,      0,      0
  },
  {
    16384, -28817,  15464
  },
  {
    16384,      0,      0
  },
  {
    16384, -32026,  16040
  },
  {
    16384,      0,      0
  },
  {
    16384, -29568,  15330
  },
  {
    16384,      0,      0
  },
  {
    16384, -31654,  15833
  },
  {
    16384,      0,      0
  },
  {
    16384, -30380,  15387
  },
  {
    16384,      0,      0
  },
  {
    16384, -31104,  15589
  },
  {
    16384,      0,      0
  }
};
