/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 23-Oct-2017 14:07:54
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,13 -> [-4 4)
 * Denominator         : s16,13 -> [-4 4)
 * Input               : s16,15 -> [-1 1)
 * Output              : s16,15 -> [-1 1)
 * Numerator Prod      : s32,28 -> [-8 8)
 * Denominator Prod    : s32,28 -> [-8 8)
 * Numerator Accum     : s40,28 -> [-2048 2048)
 * Denominator Accum   : s40,28 -> [-2048 2048)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017a/extern/include/tmwtypes.h 
 */
#define COEFFICIENTS_LENGTH 5
const Int16 NUM[5] = {
     6735, -20550,  29146, -20550,   6735
};

const Int16 DEN[5] = {
     8192, -23961,  32617, -22154,   7008
};
