/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 23-Oct-2017 10:38:36
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 3
 * Denominator Length  : 3
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : fixed
 * Numerator           : s16,21 -> [-1.562500e-02 1.562500e-02)
 * Denominator         : s16,14 -> [-2 2)
 * Input               : s16,15 -> [-1 1)
 * Output              : s16,15 -> [-1 1)
 * Numerator Prod      : s32,36 -> [-3.125000e-02 3.125000e-02)
 * Denominator Prod    : s32,29 -> [-4 4)
 * Numerator Accum     : s40,36 -> [-8 8)
 * Denominator Accum   : s40,29 -> [-1024 1024)
 * Round Mode          : convergent
 * Overflow Mode       : wrap
 * Cast Before Sum     : true
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017a/extern/include/tmwtypes.h 
 */
#define COEFFICIENTS_LENGTH 3
const Int16 NUM[3] = {
       64,    128,     64
};
const Int16 DEN[3] = {
    16384, -29743,  13615
};
